name: test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7.5'
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Prepare test data
        run: |
          pip install nnabla
          python scripts/create_test_nnp.py
      - run: npm install
      - run: npm lint:check
      - run: npm test
